name: ReadTheDocs Build

on:
  push:
    branches:
      - hotfix/readthedocs
      - master
    tags:
      - '*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger ReadTheDocs build
        uses: readthedocs/actions/preview@v1
        with:
          ebhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook-token: ${{ secrets.RTD_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}